# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_setup.ui',
# licensing of 'gui_setup.ui' applies.
#
# Created: Fri Dec 18 19:02:51 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_plot_progress = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot_progress.setGeometry(QtCore.QRect(20, 60, 210, 32))
        self.pushButton_plot_progress.setObjectName("pushButton_plot_progress")
        self.pushButton_refit_kernel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_refit_kernel.setGeometry(QtCore.QRect(700, 160, 181, 32))
        self.pushButton_refit_kernel.setObjectName("pushButton_refit_kernel")
        self.textEdit_main_out = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_main_out.setGeometry(QtCore.QRect(30, 290, 851, 231))
        self.textEdit_main_out.setObjectName("textEdit_main_out")
        self.pushButton_close_plots = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close_plots.setGeometry(QtCore.QRect(20, 250, 210, 32))
        self.pushButton_close_plots.setObjectName("pushButton_close_plots")
        self.pushButton_run_opt_step = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run_opt_step.setGeometry(QtCore.QRect(700, 254, 181, 32))
        self.pushButton_run_opt_step.setObjectName("pushButton_run_opt_step")
        self.pushButton_plot_variables = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot_variables.setGeometry(QtCore.QRect(20, 90, 210, 32))
        self.pushButton_plot_variables.setObjectName("pushButton_plot_variables")
        self.pushButton_suggest_point = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_suggest_point.setGeometry(QtCore.QRect(700, 60, 181, 32))
        self.pushButton_suggest_point.setObjectName("pushButton_suggest_point")
        self.lineEdit_beta = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_beta.setGeometry(QtCore.QRect(508, 60, 41, 20))
        self.lineEdit_beta.setObjectName("lineEdit_beta")
        self.lineEdit_gamma = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gamma.setGeometry(QtCore.QRect(508, 100, 41, 20))
        self.lineEdit_gamma.setObjectName("lineEdit_gamma")
        self.label_beta = QtWidgets.QLabel(self.centralwidget)
        self.label_beta.setGeometry(QtCore.QRect(260, 60, 221, 16))
        self.label_beta.setObjectName("label_beta")
        self.label_gamma = QtWidgets.QLabel(self.centralwidget)
        self.label_gamma.setGeometry(QtCore.QRect(260, 100, 221, 16))
        self.label_gamma.setObjectName("label_gamma")
        self.pushButton_set_beta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_beta.setGeometry(QtCore.QRect(560, 51, 121, 40))
        self.pushButton_set_beta.setObjectName("pushButton_set_beta")
        self.pushButton_set_gamma = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_gamma.setGeometry(QtCore.QRect(560, 91, 121, 40))
        self.pushButton_set_gamma.setObjectName("pushButton_set_gamma")
        self.label_opt_mode = QtWidgets.QLabel(self.centralwidget)
        self.label_opt_mode.setGeometry(QtCore.QRect(695, 10, 171, 31))
        self.label_opt_mode.setObjectName("label_opt_mode")
        self.label_current_point = QtWidgets.QLabel(self.centralwidget)
        self.label_current_point.setGeometry(QtCore.QRect(30, 10, 371, 31))
        self.label_current_point.setObjectName("label_current_point")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 40, 840, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(230, 50, 16, 230))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(690, 50, 16, 230))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_save_points = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_points.setGeometry(QtCore.QRect(700, 90, 181, 32))
        self.pushButton_save_points.setObjectName("pushButton_save_points")
        self.pushButton_add_points = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_points.setGeometry(QtCore.QRect(700, 120, 181, 32))
        self.pushButton_add_points.setObjectName("pushButton_add_points")
        self.label_best_val = QtWidgets.QLabel(self.centralwidget)
        self.label_best_val.setGeometry(QtCore.QRect(500, 10, 181, 31))
        self.label_best_val.setObjectName("label_best_val")
        self.pushButton_save_optimiser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_optimiser.setGeometry(QtCore.QRect(700, 530, 181, 32))
        self.pushButton_save_optimiser.setObjectName("pushButton_save_optimiser")
        self.checkBox_keep_running = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_keep_running.setGeometry(QtCore.QRect(770, 230, 111, 20))
        self.checkBox_keep_running.setObjectName("checkBox_keep_running")
        self.length_scale_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.length_scale_tabs.setGeometry(QtCore.QRect(250, 150, 431, 121))
        self.length_scale_tabs.setTabsClosable(False)
        self.length_scale_tabs.setObjectName("length_scale_tabs")
        self.ls_tab_1 = QtWidgets.QWidget()
        self.ls_tab_1.setObjectName("ls_tab_1")
        self.label_length_scale = QtWidgets.QLabel(self.ls_tab_1)
        self.label_length_scale.setGeometry(QtCore.QRect(10, 30, 401, 16))
        self.label_length_scale.setObjectName("label_length_scale")
        self.label_constraints = QtWidgets.QLabel(self.ls_tab_1)
        self.label_constraints.setGeometry(QtCore.QRect(10, 60, 151, 16))
        self.label_constraints.setObjectName("label_constraints")
        self.lineEdit_constraint_0 = QtWidgets.QLineEdit(self.ls_tab_1)
        self.lineEdit_constraint_0.setGeometry(QtCore.QRect(200, 60, 41, 21))
        self.lineEdit_constraint_0.setObjectName("lineEdit_constraint_0")
        self.lineEdit_constraint_1 = QtWidgets.QLineEdit(self.ls_tab_1)
        self.lineEdit_constraint_1.setGeometry(QtCore.QRect(250, 60, 41, 21))
        self.lineEdit_constraint_1.setObjectName("lineEdit_constraint_1")
        self.pushButton_set_constraints = QtWidgets.QPushButton(self.ls_tab_1)
        self.pushButton_set_constraints.setGeometry(QtCore.QRect(290, 50, 121, 40))
        self.pushButton_set_constraints.setObjectName("pushButton_set_constraints")
        self.label_obj_best_val = QtWidgets.QLabel(self.ls_tab_1)
        self.label_obj_best_val.setGeometry(QtCore.QRect(290, 10, 111, 16))
        self.label_obj_best_val.setObjectName("label_obj_best_val")
        self.length_scale_tabs.addTab(self.ls_tab_1, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 120, 210, 121))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(16, 20, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(115, 20, 60, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_plotp_obj = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_plotp_obj.setGeometry(QtCore.QRect(10, 40, 97, 26))
        self.comboBox_plotp_obj.setObjectName("comboBox_plotp_obj")
        self.comboBox_plotp_var = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_plotp_var.setGeometry(QtCore.QRect(110, 40, 93, 26))
        self.comboBox_plotp_var.setObjectName("comboBox_plotp_var")
        self.checkBox_plotp_norm = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_plotp_norm.setGeometry(QtCore.QRect(10, 70, 101, 20))
        self.checkBox_plotp_norm.setChecked(True)
        self.checkBox_plotp_norm.setObjectName("checkBox_plotp_norm")
        self.checkBox_plotp_2d = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_plotp_2d.setGeometry(QtCore.QRect(120, 70, 41, 20))
        self.checkBox_plotp_2d.setObjectName("checkBox_plotp_2d")
        self.pushButton_plot_prediction = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_plot_prediction.setGeometry(QtCore.QRect(0, 90, 210, 30))
        self.pushButton_plot_prediction.setObjectName("pushButton_plot_prediction")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.length_scale_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pushButton_plot_progress.setText(QtWidgets.QApplication.translate("MainWindow", "Plot progress", None, -1))
        self.pushButton_refit_kernel.setText(QtWidgets.QApplication.translate("MainWindow", "Refit model(s)", None, -1))
        self.pushButton_close_plots.setText(QtWidgets.QApplication.translate("MainWindow", "Close all plots", None, -1))
        self.pushButton_run_opt_step.setText(QtWidgets.QApplication.translate("MainWindow", "Run full opt step", None, -1))
        self.pushButton_plot_variables.setText(QtWidgets.QApplication.translate("MainWindow", "Plot variable values", None, -1))
        self.pushButton_suggest_point.setText(QtWidgets.QApplication.translate("MainWindow", "Suggest new points", None, -1))
        self.label_beta.setText(QtWidgets.QApplication.translate("MainWindow", "Beta:", None, -1))
        self.label_gamma.setText(QtWidgets.QApplication.translate("MainWindow", "Gamma:", None, -1))
        self.pushButton_set_beta.setText(QtWidgets.QApplication.translate("MainWindow", "Set new value", None, -1))
        self.pushButton_set_gamma.setText(QtWidgets.QApplication.translate("MainWindow", "Set new value", None, -1))
        self.label_opt_mode.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Optimisation mode: Mode</span></p></body></html>", None, -1))
        self.label_current_point.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Step n of N (point m out of M)</span></p></body></html>", None, -1))
        self.pushButton_save_points.setText(QtWidgets.QApplication.translate("MainWindow", "Save suggested points", None, -1))
        self.pushButton_add_points.setText(QtWidgets.QApplication.translate("MainWindow", "Add new points", None, -1))
        self.label_best_val.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt;\">Best summed value: nn.nn</span></p></body></html>", None, -1))
        self.pushButton_save_optimiser.setText(QtWidgets.QApplication.translate("MainWindow", "Save Optimiser", None, -1))
        self.checkBox_keep_running.setText(QtWidgets.QApplication.translate("MainWindow", " Keep running", None, -1))
        self.label_length_scale.setText(QtWidgets.QApplication.translate("MainWindow", "Length_scale:", None, -1))
        self.label_constraints.setText(QtWidgets.QApplication.translate("MainWindow", "Constraints:", None, -1))
        self.pushButton_set_constraints.setText(QtWidgets.QApplication.translate("MainWindow", "Set new values", None, -1))
        self.label_obj_best_val.setText(QtWidgets.QApplication.translate("MainWindow", "Best value:", None, -1))
        self.length_scale_tabs.setTabText(self.length_scale_tabs.indexOf(self.ls_tab_1), QtWidgets.QApplication.translate("MainWindow", "Obj 1", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Predictions", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Objective", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Variable", None, -1))
        self.checkBox_plotp_norm.setText(QtWidgets.QApplication.translate("MainWindow", "Normalised", None, -1))
        self.checkBox_plotp_2d.setText(QtWidgets.QApplication.translate("MainWindow", "3D", None, -1))
        self.pushButton_plot_prediction.setText(QtWidgets.QApplication.translate("MainWindow", "Plot predictions", None, -1))

